### PR TITLE
Merge pull request #161 from albaintor/main

### PR DESCRIPTION
**Pull request by mauro-midolo**
Upgrade with new apis

### CODE REVIEW

**Comment by kovacsla** [comment]
Hi Guys
@mauro-midolo and @albaintor 
What happened. The "https://github.com/mauro-midolo/homeassistant_electrolux_status" page doesn't answer.
Képkivágás

**Comment by wgumaa** [comment]
I just posted the same question here: 

https://github.com/Woyken/py-electrolux-ocp/issues/5

**Comment by stefanraduionescu** [comment]
Download error on home assistant, too. Unknown error

**Comment by albaintor** [comment]
This should be possible now

**Comment by stefanraduionescu** [comment]
image

**Comment by albaintor** [comment]
Hi I have been quite busy this week, I haven't followed the last events.
For now I see no reason not to continue the work as I am using a third party library still present on github. 
But things need to be clarified about the usability of theses APIs

**Comment by SmilinStanSStanman** [comment]
To install the new integration, I needed to delete the old HACS integration. Then, you have to add a new personalized repository "https://github.com/albaintor/homeassistant_electrolux_status".
With that, it is possible to install the new integration as always.

**Comment by stefanraduionescu** [comment]
Managed to install the integration v2, but i cannot find the appliance.
I enabled log and I think my account is locked. The login works fine, but it doesn't show any appliance:

024-01-31 18:07:54.566 ERROR (MainThread) [custom_components.electrolux_status] Error during login: Code 403120 (Account temporarily locked out)
Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/__init__.py", line 94, in _async_update_data
    appliances_json:list[ApplienceStatusResponse] = await self.api.get_appliances_list()
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyelectroluxocp/oneAppApi.py", line 118, in get_appliances_list
    token = await self._get_formatted_user_token()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyelectroluxocp/oneAppApi.py", line 339, in _get_formatted_user_token
    token = await self.get_user_token()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyelectroluxocp/oneAppApi.py", line 100, in get_user_token
    id_token = await gigya_client.login_user(self._username, self._password)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyelectroluxocp/gigyaClient.py", line 211, in login_user
    session = await self.login_session(username, password, gmid, ucid)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyelectroluxocp/gigyaClient.py", line 174, in login_session
    raise LoginError(f'Error during login: Code {error_code} ({error_details})')
pyelectroluxocp.gigyaClient.LoginError: Error during login: Code 403120 (Account temporarily locked out)
2024-01-31 18:07:54.941 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2024-01-31 18:07:54.942 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector
2024-01-31 18:07:54.943 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2024-01-31 18:07:54.944 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector
2024-01-31 18:08:04.327 ERROR (MainThread) [custom_components.electrolux_status] Error during login: Code 403120 (Account temporarily locked out)

**Comment by SmilinStanSStanman** [comment]
> Managed to install the integration v2, but i cannot find the appliance. I enabled log and I think my account is locked. The login works fine, but it doesn't show any appliance:
> 
> 024-01-31 18:07:54.566 ERROR (MainThread) [custom_components.electrolux_status] Error during login: Code 403120 (Account temporarily locked out) Traceback (most recent call last): File "/config/custom_components/electrolux_status/**init**.py", line 94, in _async_update_data appliances_json:list[ApplienceStatusResponse] = await self.api.get_appliances_list() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pyelectroluxocp/oneAppApi.py", line 118, in get_appliances_list token = await self._get_formatted_user_token() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pyelectroluxocp/oneAppApi.py", line 339, in _get_formatted_user_token token = await self.get_user_token() ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pyelectroluxocp/oneAppApi.py", line 100, in get_user_token id_token = await gigya_client.login_user(self._username, self._password) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pyelectroluxocp/gigyaClient.py", line 211, in login_user session = await self.login_session(username, password, gmid, ucid) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pyelectroluxocp/gigyaClient.py", line 174, in login_session raise LoginError(f'Error during login: Code {error_code} ({error_details})') pyelectroluxocp.gigyaClient.LoginError: Error during login: Code 403120 (Account temporarily locked out) 2024-01-31 18:07:54.941 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session 2024-01-31 18:07:54.942 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector 2024-01-31 18:07:54.943 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session 2024-01-31 18:07:54.944 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector 2024-01-31 18:08:04.327 ERROR (MainThread) [custom_components.electrolux_status] Error during login: Code 403120 (Account temporarily locked out)

Your phone app is working correctly? You can use it?

**Comment by stefanraduionescu** [comment]
yes, I have the new app on the phone and it seems to work ok. 
Screenshot_20240131_182305_AEG
I have turned on the appliance.. and the status is not updated in the app. I have disconnect and recoonect and it seems I am locked for 5 minutes in app too.

**Comment by stefanraduionescu** [comment]
Changed the password and I am allowed again. The app words. I connected the v2 integration and seems to work.
But there is stilI a problem. It has inherited the device and entities from the old integration, it will still try to connect with previous method..and it will block the account somehow

**Comment by stefanraduionescu** [comment]
image
it has some unavailable episodes from time to time. But works. Hope to find a way to match the previous integration entities to make my integrations work again.

**Comment by albaintor** [comment]
> @albaintor That;s good news. Do you think it's easy fix the error: AttributeError: 'NoneType' object has no attribute 'get' ?
> 
> Me and others can;'t use the integration now. When this issue is fixed, we can use it without having all the sensors etc. yet.
> 
> What is the past place to report issue? I don't think this is the best place right?

Yes this is easy to fix, I just need to have some time with my job in parallel.
Also I completely changed the model as with the older integration every entities were hardcoded in some kind of catalog.
Now the APIs return the capabilities of the appliances, which mean that now the entities will be created dynamically according to the capabilities.
The annoying thing is the units because they are not advertised, so I guess I will have to maintain some static catalog to convert to the right unit. I hope to release a new version this weekend if everything goes fine

**Pull request closed without merging**
